server:
  port: 8006
spring:
  application:
    name: PAGOS-SERVICE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:pagos-service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: info, health

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-operation-id: false
    operations-sorter: method
